version: '2'

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root123'
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306